const worklocation = [
  "New York City, New York",
  "Los Angeles, California",
  "Chicago, Illinois",
  "Houston, Texas",
  "Phoenix, Arizona",
  "Philadelphia, Pennsylvania",
  "San Antonio, Texas",
  "San Diego, California",
  "Dallas, Texas",
  "San Jose, California",
  "Austin, Texas",
  "Jacksonville, Florida",
  "San Francisco, California",
  "Columbus, Ohio",
  "Indianapolis, Indiana",
  "Fort Worth, Texas",
  "Charlotte, North Carolina",
  "Seattle, Washington",
  "Denver, Colorado",
  "Washington, D.C.",
  "Boston, Massachusetts",
  "El Paso, Texas",
  "Detroit, Michigan",
  "Nashville, Tennessee",
  "Memphis, Tennessee",
  "Portland, Oregon",
  "Oklahoma City, Oklahoma",
  "Las Vegas, Nevada",
  "Louisville, Kentucky",
  "Baltimore, Maryland",
  "Milwaukee, Wisconsin",
  "Albuquerque, New Mexico",
  "Tucson, Arizona",
  "Fresno, California",
  "Sacramento, California",
  "Kansas City, Missouri",
  "Long Beach, California",
  "Mesa, Arizona",
  "Atlanta, Georgia",
  "Colorado Springs, Colorado",
  "Miami, Florida",
  "Raleigh, North Carolina",
  "Omaha, Nebraska",
  "Oakland, California",
  "Tulsa, Oklahoma",
  "Cleveland, Ohio",
  "Wichita, Kansas",
  "Arlington, Texas",
  "New Orleans, Louisiana",
  "Tampa, Florida",
];

export default worklocation;
